### ISSUE TITLE
sh ssh problam

### ISSUE THREAD

**Issue by Altaf324** [Lemon-Hacking/Lemon#1]
when typing "sh ssh" key. so this problem is fire.    

- [ ] 

> "Please make sure you are connected to the Internet :("

**Comment by Lemon-Hacking** [comment]
It happens when you have a slow Internet connection or some other issue I don't know about yet. Try reinstalling the script and ensuring you have a good Internet Connection.

**Comment by Lemon-Hacking** [comment]
Serveo is currently down, instead of Serveo, localhost?run has been added, so it will generate a link now!
