### ISSUE TITLE
sh shh error

### ISSUE THREAD

**Issue by Isururanjana** [Lemon-Hacking/Lemon#2]
sh shh - not generate any link.

**Comment by Lemon-Hacking** [comment]
It should generate a link, if it does not, then you either have a slow connection or some other issue not yet known by me, try reinstalling and checking your Internet connection's speed and ensuring it is enough.

**Comment by Lemon-Hacking** [comment]
Serveo is currently down, it will be up in a few days, Ngrok has been added, though it requires cellular data, ( HotSpot must be turned on )

**Comment by Lemon-Hacking** [comment]
Serveo is currently down, it will be up in a few days, instead of Serveo, localhost.run has been added, so it will generate a link now!
