### ISSUE TITLE
Sh sah problem 

### ISSUE THREAD

**Issue by Manish347** [Lemon-Hacking/Lemon#4]
![Screenshot_2020-03-08-16-34-21-47_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/61860765/76161606-f5fa6480-615a-11ea-9d16-e43001b01762.png)

How to move to the next part of i preess y it steel shows error
 Sorry for wrong title its "sh ssh"

**Comment by Lemon-Hacking** [comment]
Fixed. The script has been updated, read README.md for instructions.
